import { defineConfig } from '@playwright/test';
import path from 'node:path';

/**
 * End-to-end tests drive the real app in a headless browser with a file-backed fake camera.
 * Chromium's synthetic fake camera stops after ~1.5 s in current headless builds, so the
 * clip generated by e2e/fixtures/make-fake-camera.mjs is required (see globalSetup).
 *
 * PW_CHANNEL=msedge|chrome uses an installed browser instead of Playwright's Chromium.
 */
const PORT = 4311;
const FAKE_CAMERA = path.resolve(process.cwd(), 'e2e/fixtures/fake-cam.y4m');

export default defineConfig({
  testDir: './e2e',
  globalSetup: './e2e/global-setup.ts',
  timeout: 120_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  workers: 1,
  retries: process.env['CI'] ? 1 : 0,
  reporter: process.env['CI'] ? [['list'], ['html', { open: 'never' }]] : 'list',
  use: {
    baseURL: `http://localhost:${PORT}`,
    viewport: { width: 390, height: 844 },
    permissions: ['camera', 'microphone', 'clipboard-read', 'clipboard-write'],
    acceptDownloads: true,
    trace: 'retain-on-failure',
    channel: process.env['PW_CHANNEL'] || undefined,
    launchOptions: {
      args: [
        '--use-fake-device-for-media-stream',
        '--use-fake-ui-for-media-stream',
        `--use-file-for-fake-video-capture=${FAKE_CAMERA.replace(/\\/g, '/')}`,
      ],
    },
  },
  webServer: {
    command: `npx ng serve --port ${PORT}`,
    url: `http://localhost:${PORT}`,
    reuseExistingServer: !process.env['CI'],
    timeout: 240_000,
  },
});
