// Generates src/environments/env.secrets.ts from environment variables, falling back to
// a git-ignored .env.local file. Runs before install/start/build/test so a fresh clone
// always compiles; missing values become empty strings and the app degrades gracefully
// (same-browser signaling, STUN only). Never prints values, only which names were set.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const KEYS = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'TURN_USERNAME', 'TURN_CREDENTIAL'];

const fromFile = {};
const envFile = resolve(root, '.env.local');
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/.exec(line);
    if (m && !line.trim().startsWith('#')) fromFile[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}

const values = Object.fromEntries(KEYS.map((k) => [k, process.env[k] ?? fromFile[k] ?? '']));
const esc = (v) => JSON.stringify(String(v));
const out = `// Generated by scripts/write-env.mjs. Do not edit, do not commit.
export const SECRETS = {
  supabaseUrl: ${esc(values.SUPABASE_URL)},
  supabaseAnonKey: ${esc(values.SUPABASE_ANON_KEY)},
  turnUsername: ${esc(values.TURN_USERNAME)},
  turnCredential: ${esc(values.TURN_CREDENTIAL)},
} as const;
`;
const target = resolve(root, 'src/environments/env.secrets.ts');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out);
const set = KEYS.filter((k) => values[k]);
console.log(`env.secrets.ts written (${set.length ? 'set: ' + set.join(', ') : 'no secrets set, using local fallbacks'})`);
